version: '2'
services:
  # databases
  postgres:
    image: postgres:9.6.1
    expose:
      - "5432"
    environment:
      POSTGRES_USER: metronome
      POSTGRES_PASSWORD: metropass
      POSTGRES_DB: metronome
  redis:
    image: redis:3.2.6

  # kafka
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    links:
      - zookeeper
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "tasks:1:1:compact,jobs:1:1,states:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  ui:
    build: git://github.com/ovh/metronome-ui
    ports:
      - "8080:8080"

  init_db:
    links:
      - postgres
    build: .
    command: ./wait-for-it.sh postgres:5432 -- metronome-api init-database --pg.addr=postgres:5432

  api:
    links:
      - init_db
      - kafka
      - redis
    build: .
    ports:
      - "8081:8080"
    command: ./wait-for-it.sh kafka:9092 -- metronome-api --pg.addr=postgres:5432 --kafka.brokers=kafka:9092 --redis.addr=redis:6379
  scheduler:
    links:
      - kafka
    build: .
    command: ./wait-for-it.sh kafka:9092 -- metronome-scheduler --kafka.brokers=kafka:9092 --redis.addr=redis:6379
  aggregator:
    links:
      - postgres
      - kafka
      - redis
    build: .
    command: ./wait-for-it.sh kafka:9092 -- metronome-aggregator --pg.addr=postgres:5432 --kafka.brokers=kafka:9092 --redis.addr=redis:6379
  worker:
    links:
      - kafka
    build: .
    command: ./wait-for-it.sh kafka:9092 -- metronome-worker --kafka.brokers=kafka:9092
